### ISSUE TITLE
link does not display

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#10]
@punkish here is bug that does not allow to scroll down to the link to the BLR page:

![image](https://user-images.githubusercontent.com/4609956/39866582-84cdab72-5451-11e8-82f1-05b5425e2b53.png)

it only works, if one zooms considerable out

![image](https://user-images.githubusercontent.com/4609956/39866528-576fbae4-5451-11e8-981c-1d8bd362f501.png)

**Comment by punkish** [comment]
fixed. Thanks for reporting.
