### ISSUE TITLE
ocellus v 2: bug

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#12]
ending in nowhere: When moving from on page to the next, and arriving on the "next" that has no images anymore, you end up with a blank page, where it is impossible to get back to the previous search 
https://ocellus.punkish.org/?q=xiphocentron&page=1
and here is the next page that is just a blank, starting page with no memory of the previous search, neither a link to the first page

![image](https://user-images.githubusercontent.com/4609956/41833031-f86aa456-784e-11e8-808c-ba21e528e52a.png)

**Comment by punkish** [comment]
couldn't reproduce this
