### ISSUE TITLE
"phylogeny" returns mostly not phylogenies

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#19]
https://ocellus.info/images.html?q=%22phylogeny%22&size=75&page=4&communities=biosyslit

the results of Ocellus are misleading: A large part of the images retuned on the term "phylogeny" have nothing to do with phylogenies other than that somewhere in another part of the publications there is phylogeny.

For me this is misleading and takes part of the elegance of Ocellus. May be we should have two ways to search it. One restricted to terms in the caption or the metadata, the other the way you have implemented it.

![image](https://user-images.githubusercontent.com/4609956/112432953-e340d680-8d41-11eb-9e6b-61383159a3c2.png)

vs this, what I would expect
![image](https://user-images.githubusercontent.com/4609956/112432768-a1b02b80-8d41-11eb-9738-7b456e635f63.png)

This also raises the question, why I get only phylogenies when I get 30 figures back as opposed when I get 75?

**Comment by punkish** [comment]
I think I have a possible solution for this, but it will take some time to implement it (and lots of testing). I will keep this issue open and update it when I have something working
