### ISSUE TITLE
new version of the Ocellus/Zenodeo

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#25]
Hello everyone,

I am very happy to have pushed a new version of the Ocellus/Zenodeo apps. They are both live at

https://ocellus.info/
https://test.zenodeo.org/

I am in the process of writing some explanatory release notes on their respective Github repos, but here is a quick summary:

1. Zenodeo supports a slew of extended querying capabilities. The full details are documented on the Zenodeo website under each resource that can be fetched from the database. For example, 

	- fields with dates (publicationDate, checkinTime) can be queried like so

	publicationDate=since(2010-12-21)
	publicationDate=until(2000-01-01)
	checkinTime=between(2012-01-17 and 2013-12-12)
	checkinTime=eq(2013-12-03)

	- geolocation can be queried like so

	geolocation=within({radius:100, units: ‘kilometers’, lat: -43.05, lng: -121.223})
	geolocation=containedIn({lowerLeft:{lat: 5, lng: 7}, upperRight:{lat: 22, lng: 13}})

For the most part, one would construct these queries programmatically instead of by hand. Already, every field extracted from the XMLs is queryable, but I hope to expand this extended query capability much further. Your feedback would be very welcome.

2. As an image explorer, Ocellus is made possible by Zenodeo, and the new version leverages the new querying capabilities. You can, of course, search for images as usual, by just typing some text and letting Ocellus do a full-text search on both images on Zenodo (that is, images that may have nothing to do with treatments) as well as images connected to treatments. Ocellus combines the two results, weeds out the duplicates and presents the images in a unified view.

But, you can also use the extended queries on Ocellus (currently only possible against treatments, but hopefully, eventually expanded to include all of Zenodo images).

You will notice the same, minimalistic Ocellus interface but with two new features — a switch that selects the source of images (this switch automatically selects treatments as a source if it detects extended queries), and a link to example searches that reveals examples of extended queries. Clicking on an example fills the form correctly. You just have to press [go] to retrieve the images.

Whatever source you choose, the images connected to treatments are marked with a [T] on the upper right corner which reveals the treatmentId when you click on it. These images also have a link to the respective record on TreatmentBank.

Ocellus has been rewritten using the new ES6 module syntax, and as a result, the code is much cleaner, smaller, and hopefully more bug-free. (I want the only bugs to be the ones you are viewing on the screen.)

Speed and clarity are the prime-objective in making Ocellus, and I happy to say, it excels at those. I tested Ocellus against pagespeed.web.dev and it comes up at 100/100 on desktop and 97/100 on mobile. The entire application is around 350 KB and works great on phones.

Please use, test, and report any issues you may experience on the issue-trackers of the respective applications.

A lot more to come,

Puneet

**Comment by punkish** [comment]
hello everyone,

I have now added a cache-busting mechanism to Ocellus so it is no longer necessary (or, I might say, it should not be necessary) to refresh/empty your browser cache to get the latest version of the ocellus javascript and css. Every time I make any change, a new version with a unique name is generated so the browser will always cache only the latest version.

@millerjeremy @myrmoteras
