### ISSUE TITLE
new version of ocellus: display distance between thumbnails

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#26]
it seems that the display of ocellus has been changed.

![image](https://user-images.githubusercontent.com/4609956/154368902-ad86543c-df5d-47e9-b13d-22211f23a360.png)

I preferred the older verison where the thumbnails have been much closer to each other like this

![image](https://user-images.githubusercontent.com/4609956/154369188-2c1a07a7-1254-475e-a328-806871ed8be4.png)

**Comment by punkish** [comment]
yea, you are right, the older version looks much nicer. The weird thing is, you shouldn't be seeing those gaps. Please do the following… reproduce the above display (the one with the ugly gaps) and let me know what display resolution is your screen. Thanks

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/155295034-bf54362e-f9a4-4ebe-8473-88a619ba1e4f.png)
3840 x 2160

**Comment by punkish** [comment]
hi @myrmoteras,

I have pushed a fix for the column gap. Please try again, but first, make sure you empty your browser cache so you get the latest stylesheet as the default caching is very aggressive. If you don't see the fix, try the following

1. go to https://ocellus.info/css/ocellus.min.css  
2. then press Cmd (or Ctrl on Windows, I think) and reload the page  
3. search (Ctrl-F) for `#grid-images`. If you find it, then you have the latest css
4. go back and reload your ocellus search

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/155302994-0833a37a-cb66-4bef-85b7-9ab7133b50f8.png)


here it is . 
* top Firerfox that does what you want.
* below Google Chrome which does it the old way.

I don't want to clear cache because there is too much inside that makes my life easier. 

But what you can see is that GC has more image per row - what I prefer - and the distances between the images vary depending on the size of the window. In FF the distance does not change

**https://ocellus.info/?source=all&q=Nymphalidae&page=1&size=30**

**Comment by punkish** [comment]
yea, it should behave the same way on all the major browsers. Unfortunately there is no way for you to see it in Chrome unless you clear the cache. That is just how the computer works. I am sending it the right css but your Chrome is using the old one. If you clear the cache, it should pick up the new css. If you don't want to clear the entire cache, maybe there is a way to clear only the cache related to ocellus.info domain, but I don't know how. Try the four steps I listed above (with Chrome) and see if that helps

**Comment by myrmoteras** [comment]
at some point I will. Right now I just use FF for this purpose
