### ISSUE TITLE
Screenshot (17 Feb 2022 07:11:21)

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#28]
http://treatment.plazi.org/id/D7781AC6-EB44-4863-BFAC-8FA15FE24A21

https://ocellus.info/?source=all&q=Tyrannoscelio&page=1&size=30

Missing images in Ocellus![Screenshot_20220217-071121.png](https://user-images.githubusercontent.com/4609956/154416448-636421cf-26a5-42e3-ae05-7735541a7075.png)

**Comment by punkish** [comment]
@myrmoteras please try again. I am not able to reproduce it so it is possible that you hit that when there was a gap in the database. Ordinarily, that should not happen, so I can't figure out right away why you experienced the above. But if it does again, please let me know.
