### ISSUE TITLE
Caption

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#3]
Add figure legend, citation detail (?) in a pop-up menu or other that appears when themouse is over the object. This would reduce permanent space usage

**Comment by myrmoteras** [comment]
now that figure legends can be seen, it might be helpful to be a able to keep selected captions open?

**Comment by punkish** [comment]
The caption that is opened remains open until a new caption is opened. Only then an existing open caption is closed. A caption can also be closed manually by clicking on the record ID with the wavy underline. If users strongly feel that open captions should remain open even when new captions are opened, I could certainly implement that. But let's wait and see.
