### ISSUE TITLE
link dead

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#31]
the link to Zenodeo is dead https://ocellus.info/#about

```
// 20220816103915
// https://zenodeo.org/

{
  "error": "404 Error! Page Not Found! You might want to start at the root",
  "root": "https://zenodeo.org/v2"
}

```

**Comment by punkish** [comment]
> the link to Zenodeo is dead https://ocellus.info/#about

The above is the link to ocellus, not zenodeo

That said, the link to zenodeo is working fine. The root link for zenodeo is https://zenodeo.org/v2 but that is the old version, and I would really like to retire it. The new version is at https://test.zenodeo.org/v3 or just https://test.zenodeo.org where you can read an html page with all the documentation
