### ISSUE TITLE
number of pages does not work

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#32]
if I want to download a different number of hits than the default, I can't.

https://ocellus.info/?source=all&q=scaritinae&page=1&size=30

3'0 replaced with 50 or 100 does not work

https://ocellus.info/?source=all&q=scaritinae&page=1&size=100 does not work

**Comment by punkish** [comment]
sorry for the delay in responding to this… all of the following links seem to work

https://ocellus.info/?source=all&q=scaritinae&page=1&size=30
https://ocellus.info/?source=all&q=scaritinae&page=1&size=50
https://ocellus.info/?source=all&q=scaritinae&page=1&size=100

only 92 images exist for "scaritinae"
