### ISSUE TITLE
doi can't be used for search

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#35]
I am trying to find all the image within on article using the doi: eg [10.5852/ejt.2023.866.2107](https://doi.org/10.5852/ejt.2023.866.2107) but I get a 500 error

https://ocellus.info/?page=1&size=30&resource=images&q=10.5852%2Fejt.2023.866.2107

![image](https://user-images.githubusercontent.com/4609956/237039855-9e9cdf73-06c0-47a0-9c80-c3a5bcf6e245.png)

similarly, if I search using part of the title "Morphology and taxonomic assessment of eight genetic clades of Mercuria Boeters, 1971"  https://ocellus.info/?page=1&size=30&resource=images&q=Morphology+and+taxonomic+assessment+of+eight+genetic+clades+of+Mercuria+Boeters%2C+1971

![image](https://user-images.githubusercontent.com/4609956/237040225-6990e90c-1e88-4f51-9baf-500ccac12abf.png)

**Comment by punkish** [comment]
this is working now. And now you can just type the DOI `10.5852/ejt.2023.866.2107` in the search box with the leading `articleDOI=10.5852/ejt.2023.866.2107`. Note, this facility works *only* for `articleDOI`s, and even so, the URI will still show `articleDOI=10.5852/ejt.2023.866.2107`
