### ISSUE TITLE
odd search results

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#37]
this search results mainly in wrong - not expected resutls. That is it shows images of taxa that have nothing to do with shrimp.
https://ocellus.info/?page=1&size=30&resource=images&q=shrimp&publicationDate=since%282020-12-21%29

![image](https://github.com/punkish/ocellus/assets/4609956/d43e3872-5dd8-412e-bf8e-04a3f874a324)

**Comment by punkish** [comment]
thanks for pointing this out. I think there was something wrong with the search index. Try it now. I seem to get the correct results now https://ocellus.info/?page=1&size=30&resource=images&q=shrimp&publicationDate=since%282020-12-21%29
