### ISSUE TITLE
documentation for the use of ocellus and terms used

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#38]
with  adding a short table of the queries into the "about" popup, the use of ocellus could be much improved:

just a list like
* articleDOI= XXX search for images in an article, e.g. 
* journalTitle=eq(XXX)
* articleTitle=starts_with(XXX)
* geolocation=within(radius:10,units:'kilometers',lat:40.21,lng:-120.33)
* checkinTime=between(2021-12-01 and 2021-12-31)
* Author?=  
would be helpful for beginners

the terms you use for the searches, what is there origin? Do they correspond to a reference vocabulary? eg [Zenodo](https://developers.zenodo.org/?javascript#quickstart-upload) or DWC in GBIF or [NCBI](https://www.ncbi.nlm.nih.gov/pmc/advanced)?

**Comment by punkish** [comment]
already exists… see the screenshot below

![ocellue-help](https://github.com/punkish/ocellus/assets/349242/be38342e-d004-4a69-a135-bd4698daa00e)
