### ISSUE TITLE
checkinTime does not work

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#42]
I tried this https://ocellus.info/?page=3&size=30&resource=images&checkinTime=since%2806-06-2023%29
and this this

![image](https://github.com/punkish/ocellus/assets/4609956/85f20d7c-e854-4d56-bc63-d7c470d38046)

you might also want to write

**Comment by punkish** [comment]
see https://github.com/punkish/ocellus/issues/43#issuecomment-1587948445
