### ISSUE TITLE
why such a lag time to get images into ocellus

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#43]
today 2023-06-08  I only get images from 2023-05-26. Why such a long time lag, whilst you have a model question to get the images from yesterday?

https://ocellus.info/?page=3&size=30&resource=images&checkinTime=since%2806-06-2023%29

![image](https://github.com/punkish/ocellus/assets/4609956/058d4329-bb53-46ef-b812-b0dc9e0a9607)

**Comment by punkish** [comment]
This is because of a mistake on my part, sorry about that. I will let you know as soon as I have a fix implemented and tested

**Comment by punkish** [comment]
hi @myrmoteras this is fixed for now although I intend to continue to work on the fix to make it more robust. Just one note… the date format is `yyyy-mm-dd`, so the following URL that you provided above has the date wrong. I show both, the wrong version first and the correct version after. Hope this helps

```js
// wrong version
https://ocellus.info/?page=1&size=30&resource=images&checkinTime=since(06-06-2023)

// correct version (note, the year comes first, then the month, then the day)
https://ocellus.info/?page=1&size=30&resource=images&checkinTime=since(2023-06-06)
```
