### ISSUE TITLE
new search interface

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#49]
I started searching for authority Agosti, knowing that there are some https://tb.plazi.org/GgServer/srsStats/stats?outputFields=bib.year+tax.name+tax.authName&groupingFields=bib.year+tax.name+tax.authName&FP-tax.authName=%25Agosti%25&format=HTML

1. the box new species can't be checked
2. when I add "Agosti" in authority and year 2011 I don't get any response
3. when I add "Agosti" into full text I am getting a response
4. I can't go back to modify the search
5. when I search for "Agosti" in authority and enter "2029" for year I am getting the result
6. Is there a wild card or how to find "Collingwood & Agosti" as authority?
7. to move from query to result via the bottom upper right is not really intuitive, but by chance discoverable
8. it would be helpful to search for a range of years
9. Search for Biome without help is not really easy

**Comment by punkish** [comment]
there are a lot of issues in here (9 different things). I am looking into them one by one and will fix all of them. Thanks for the report.

**Comment by punkish** [comment]
> 6. Is there a wild card or how to find "Collingwood & Agosti" as authority?

Luckily this is as easy as typing "Collingwood & Agosti" in the search field. See link below

https://ocellus.info/index.html?resource=images&authorityName=Collingwood+%26+Agosti

**Comment by punkish** [comment]
> 5. when I search for "Agosti" in authority and enter "2029" for year I am getting the result

I am assuming you meant to type "2019" there as 2029 hasn't happened yet. So, what is the problem?

**Comment by punkish** [comment]
- biome search is fixed
- new sp. checkbox can now be checked
- "Collingwood & Agosti" in authority field works just fine
- agosti fulltext search works fine
