### ISSUE TITLE
ocellus 2: layout

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#5]
The layout of ocellus 2 is detrimental to the slik layout you had before

![image](https://user-images.githubusercontent.com/4609956/36143666-02430c4e-10ac-11e8-8c69-c92a03831e9f.png)

the gray box for the search terms should be rounded and in line with the other terms. Right now, the term is lowered

**Comment by punkish** [comment]
the path to Ocellus 2 has become a bit longer. As such, a more precise layout has been implemented with no new visible functionality but the internal core re-written for more flexibility later. Also, many bugs have been closed either via Ocellus or via Zenodeo fixes.
