### ISSUE TITLE
does not display figures

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#50]
When I searching this URL then I do not get any figures
https://ocellus.info/index.html?page=4&size=30&resource=images&status=sp.+nov.&checkinTime=since%282024-02-02%29
![image](https://github.com/punkish/ocellus/assets/4609956/51dcef52-e57a-47a8-b4c1-5f69b60c8362)

**Comment by punkish** [comment]
this works fine for me although it is slow. I will look into the speed issue although I know a part of the slowness is because Contabo's server configuration is much slower than my laptop. I will also explore increasing the server configuration to improve the performance.

**Comment by myrmoteras** [comment]
Why not ask Guido to use the Frankfurt server?

**Comment by punkish** [comment]
> Why not ask Guido to use the Frankfurt server? 


Lots of reasons… I need a VPS, not an existing server, so I can install my own set of needed software. That way, if I screw up something, I don't screw up everything. The damage is limited to a small server that can be easily rebuilt. Plus, I need root access. Frankfurt server is doing mission critical things to our work and there really shouldn't be any user-land projects on it.

Upgrading Contabo will be cheap and easy.
