### ISSUE TITLE
broken link for zenodeo.api

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#51]
@punkish the link in https://ocellus.info/ to https://test.zenodeo.org/ is broken. 
![image](https://github.com/punkish/ocellus/assets/4609956/8e2da031-e1f9-4ea5-9906-820358157555)

![image](https://github.com/punkish/ocellus/assets/4609956/535078ef-c1b2-433e-a318-011bdd187162)

same from here https://plazi.org/data-apis-tools/zenodeo/

Can you please provide a link to the zenodeo.api?

tx

**Comment by punkish** [comment]
thanks for reporting… for some reason the process had crashed. The link is correct though. Note that the first link below is to the website which shows all the documentation, and the second link is where actually queries are made. The third link show an example of querying for treatments

```
https://test.zenodeo.org
https://test.zenodeo.org/v3/
https://test.zenodeo.org/v3/treatments
```
