### ISSUE TITLE
additional data of images

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#7]
A suggestion: would it be possible to change the display of caption information as a popup window instead of a fixed window?

![image](https://user-images.githubusercontent.com/4609956/36376969-7bedd6e6-1575-11e8-9581-04f3e463f028.png)

**Comment by punkish** [comment]
sorry no. Popup windows don't belong in web applications. They are disruptive and they make it very hard to track state. Plus, there is no concept of popup windows in mobile apps, and Ocellus will always remain a mobile-first app. You might want to provide a reason why you don't like the current implementation, and we can try and make the current experience better.
