### ISSUE TITLE
ocellus2 does not work

### ISSUE THREAD

**Issue by myrmoteras** [punkish/ocellus#8]
when running a second search, then ocellus2 does not work anymore.

e.g.
1. Search: Family = Serrassalmidae - result ok
2. Search: Author = Baur, Hannes - no reaction https://ocellus.punkish.org/index2.html?q=%2Btitle%3A(%22Serrasalmidae%22)&page=1

**Comment by punkish** [comment]
As mentioned elsewhere, the fancy search capabilities of Ocellus2 have been sidelined, for now. They will come back, but via a longer route. Ocellus2 is now active with the same functionality as Ocellus1, but rewritten from the inside out.
